name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - '!README.md'
      - '!.github/**'
      - '.github/workflows/Docker.yaml'
      - '!mkdocs.yml'
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 720
    strategy:
      matrix:
        runs_on: [ubuntu-22.04, macos-14] # macos-14 is added for arm support. See also https://x.com/github/status/1752458943245189120?s=20
    steps:
      - name: Install docker for mac runner
        if: ${{ matrix.runs_on == 'macos-14'}}
        run: |
          brew install wget
          wget "https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-arm64&_gl=1*aalniu*_ga*MTQ5MTgxNTA3NC4xNzA1OTE2NzEw*_ga_XJWPQMJYHQ*MTcwODAwMzc5Ni43LjEuMTcwODAwMzk0Ni41Ny4wLjA." -O Docker.app
          hdiutil attach Docker.dmg
          /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license
          hdiutil detach /Volumes/Docker

      - name: Install docker for ubuntu runner
        if: ${{ matrix.runs_on == 'ubuntu-22.04' }}
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (amd64)
        uses: docker/bake-action@v3
        if: ${{ matrix.runs_on == 'ubuntu-22.04' }}
        with:
          files: |
            ./docker-bake.hcl
          workdir: .
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          set: |
            *.platform=linux/amd64

      - name: Build and push (arm64)
        uses: docker/bake-action@v3
        if: ${{ matrix.runs_on == 'macos-14'}}
        with:
          files: |
            ./docker-bake.hcl
          workdir: .
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          set: |
            *.platform=linux/arm64/v8
